config/routes.rb
Knktr3::Application.routes.draw do
  resources :clicks

  resources :analytics

  get "pages/about"
  get "pages/contact"

  resources :users

  resources :httpstatuses

  resources :links

  resources :short_url, :only => [:index, :show]
  

  root :to => 'links#new'
  match '/:id' => 'short_url#show'

end

app/models/analytic.rb
class Analytic < ActiveRecord::Base
  attr_accessible :clickcount, :link_id, :short_url_id
end

app/controllers/analytics_controller.rb
class AnalyticsController < ApplicationController
  # GET /analytics
  # GET /analytics.json
  def index
    @analytics = Analytic.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @analytics }
    end
  end

  # GET /analytics/1
  # GET /analytics/1.json
  def show
    @analytic = Analytic.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @analytic }
    end
  end

  # GET /analytics/new
  # GET /analytics/new.json
  def new
    @analytic = Analytic.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @analytic }
    end
  end

  # GET /analytics/1/edit
  def edit
    @analytic = Analytic.find(params[:id])
  end

  # POST /analytics
  # POST /analytics.json
  def create
    @analytic = Analytic.new(params[:analytic])

    respond_to do |format|
      if @analytic.save
        format.html { redirect_to @analytic, notice: 'Analytic was successfully created.' }
        format.json { render json: @analytic, status: :created, location: @analytic }
      else
        format.html { render action: "new" }
        format.json { render json: @analytic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /analytics/1
  # PUT /analytics/1.json
  def update
    @analytic = Analytic.find(params[:id])

    respond_to do |format|
      if @analytic.update_attributes(params[:analytic])
        format.html { redirect_to @analytic, notice: 'Analytic was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @analytic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /analytics/1
  # DELETE /analytics/1.json
  def destroy
    @analytic = Analytic.find(params[:id])
    @analytic.destroy

    respond_to do |format|
      format.html { redirect_to analytics_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/analytics_helper.rb
module AnalyticsHelper
end

app/views/analytics/_form.html.erb
<%= form_for(@analytic) do |f| %>
  <% if @analytic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@analytic.errors.count, "error") %> prohibited this analytic from being saved:</h2>

      <ul>
      <% @analytic.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :link_id %><br />
    <%= f.text_field :link_id %>
  </div>
  <div class="field">
    <%= f.label :short_url_id %><br />
    <%= f.text_field :short_url_id %>
  </div>
  <div class="field">
    <%= f.label :clickcount %><br />
    <%= f.number_field :clickcount %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/analytics/edit.html.erb
<h1>Editing analytic</h1>

<%= render 'form' %>

<%= link_to 'Show', @analytic %> |
<%= link_to 'Back', analytics_path %>

app/views/analytics/index.html.erb
<h1>Listing analytics</h1>

<table>
  <tr>
    <th>Link</th>
    <th>Short url</th>
    <th>Clickcount</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @analytics.each do |analytic| %>
  <tr>
    <td><%= analytic.link_id %></td>
    <td><%= analytic.short_url_id %></td>
    <td><%= analytic.clickcount %></td>
    <td><%= link_to 'Show', analytic %></td>
    <td><%= link_to 'Edit', edit_analytic_path(analytic) %></td>
    <td><%= link_to 'Destroy', analytic, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Analytic', new_analytic_path %>

app/views/analytics/new.html.erb
<h1>New analytic</h1>

<%= render 'form' %>

<%= link_to 'Back', analytics_path %>

app/views/analytics/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Link:</b>
  <%= @analytic.link_id %>
</p>

<p>
  <b>Short url:</b>
  <%= @analytic.short_url_id %>
</p>

<p>
  <b>Clickcount:</b>
  <%= @analytic.clickcount %>
</p>


<%= link_to 'Edit', edit_analytic_path(@analytic) %> |
<%= link_to 'Back', analytics_path %>