config/routes.rb
Knktr3::Application.routes.draw do
  resources :clicks

  resources :analytics

  get "pages/about"
  get "pages/contact"

  resources :users

  resources :httpstatuses

  resources :links

  resources :short_url, :only => [:index, :show]
  

  root :to => 'links#new'
  match '/:id' => 'short_url#show'

end

app/controllers/httpstatuses_controller.rb
class HttpstatusesController < ApplicationController
  # GET /httpstatuses
  # GET /httpstatuses.json
  def index
    @httpstatuses = Httpstatus.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @httpstatuses }
    end
  end

  # GET /httpstatuses/1
  # GET /httpstatuses/1.json
  def show
    @httpstatus = Httpstatus.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @httpstatus }
    end
  end

  # GET /httpstatuses/new
  # GET /httpstatuses/new.json
  def new
    @httpstatus = Httpstatus.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @httpstatus }
    end
  end

  # GET /httpstatuses/1/edit
  def edit
    @httpstatus = Httpstatus.find(params[:id])
  end

  # POST /httpstatuses
  # POST /httpstatuses.json
  def create
    @httpstatus = Httpstatus.new(params[:httpstatus])

    respond_to do |format|
      if @httpstatus.save
        format.html { redirect_to @httpstatus, notice: 'Httpstatus was successfully created.' }
        format.json { render json: @httpstatus, status: :created, location: @httpstatus }
      else
        format.html { render action: "new" }
        format.json { render json: @httpstatus.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /httpstatuses/1
  # PUT /httpstatuses/1.json
  def update
    @httpstatus = Httpstatus.find(params[:id])

    respond_to do |format|
      if @httpstatus.update_attributes(params[:httpstatus])
        format.html { redirect_to @httpstatus, notice: 'Httpstatus was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @httpstatus.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /httpstatuses/1
  # DELETE /httpstatuses/1.json
  def destroy
    @httpstatus = Httpstatus.find(params[:id])
    @httpstatus.destroy

    respond_to do |format|
      format.html { redirect_to httpstatuses_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/httpstatuses_helper.rb
module HttpstatusesHelper
end

app/views/httpstatuses/_form.html.erb
<%= form_for(@httpstatus) do |f| %>
  <% if @httpstatus.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@httpstatus.errors.count, "error") %> prohibited this httpstatus from being saved:</h2>

      <ul>
      <% @httpstatus.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :status_code %><br />
    <%= f.text_field :status_code %>
  </div>
  <div class="field">
    <%= f.label :link_id %><br />
    <%= f.number_field :link_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/httpstatuses/edit.html.erb
<h1>Editing httpstatus</h1>

<%= render 'form' %>

<%= link_to 'Show', @httpstatus %> |
<%= link_to 'Back', httpstatuses_path %>

app/views/httpstatuses/index.html.erb
<h1>Listing httpstatuses</h1>

<table>
  <tr>
    <th>Status code</th>
    <th>Link</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @httpstatuses.each do |httpstatus| %>
  <tr>
    <td><%= httpstatus.status_code %></td>
    <td><%= httpstatus.link_id %></td>
    <td><%= link_to 'Show', httpstatus %></td>
    <td><%= link_to 'Edit', edit_httpstatus_path(httpstatus) %></td>
    <td><%= link_to 'Destroy', httpstatus, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Httpstatus', new_httpstatus_path %>

app/views/httpstatuses/new.html.erb
<h1>New httpstatus</h1>

<%= render 'form' %>

<%= link_to 'Back', httpstatuses_path %>

app/views/httpstatuses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Status code:</b>
  <%= @httpstatus.status_code %>
</p>

<p>
  <b>Link:</b>
  <%= @httpstatus.link_id %>
</p>


<%= link_to 'Edit', edit_httpstatus_path(@httpstatus) %> |
<%= link_to 'Back', httpstatuses_path %>