config/routes.rb
Knktr3::Application.routes.draw do
  resources :clicks

  resources :analytics

  get "pages/about"
  get "pages/contact"

  resources :users

  resources :httpstatuses

  resources :links

  resources :short_url, :only => [:index, :show]
  

  root :to => 'links#new'
  match '/:id' => 'short_url#show'

end

app/models/click.rb
class Click < ActiveRecord::Base
  attr_accessible :clickdate, :ip, :referer
end

app/controllers/clicks_controller.rb
class ClicksController < ApplicationController
  # GET /clicks
  # GET /clicks.json
  def index
    @clicks = Click.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @clicks }
    end
  end

  # GET /clicks/1
  # GET /clicks/1.json
  def show
    @click = Click.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @click }
    end
  end

  # GET /clicks/new
  # GET /clicks/new.json
  def new
    @click = Click.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @click }
    end
  end

  # GET /clicks/1/edit
  def edit
    @click = Click.find(params[:id])
  end

  # POST /clicks
  # POST /clicks.json
  def create
    @click = Click.new(params[:click])

    respond_to do |format|
      if @click.save
        format.html { redirect_to @click, notice: 'Click was successfully created.' }
        format.json { render json: @click, status: :created, location: @click }
      else
        format.html { render action: "new" }
        format.json { render json: @click.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /clicks/1
  # PUT /clicks/1.json
  def update
    @click = Click.find(params[:id])

    respond_to do |format|
      if @click.update_attributes(params[:click])
        format.html { redirect_to @click, notice: 'Click was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @click.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clicks/1
  # DELETE /clicks/1.json
  def destroy
    @click = Click.find(params[:id])
    @click.destroy

    respond_to do |format|
      format.html { redirect_to clicks_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/clicks_helper.rb
module ClicksHelper
end

app/views/clicks/_form.html.erb
<%= form_for(@click) do |f| %>
  <% if @click.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@click.errors.count, "error") %> prohibited this click from being saved:</h2>

      <ul>
      <% @click.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :referer %><br />
    <%= f.text_field :referer %>
  </div>
  <div class="field">
    <%= f.label :ip %><br />
    <%= f.text_field :ip %>
  </div>
  <div class="field">
    <%= f.label :clickdate %><br />
    <%= f.datetime_select :clickdate %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/clicks/edit.html.erb
<h1>Editing click</h1>

<%= render 'form' %>

<%= link_to 'Show', @click %> |
<%= link_to 'Back', clicks_path %>

app/views/clicks/index.html.erb
<h1>Listing clicks</h1>

<table>
  <tr>
    <th>Referer</th>
    <th>Ip</th>
    <th>Clickdate</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @clicks.each do |click| %>
  <tr>
    <td><%= click.referer %></td>
    <td><%= click.ip %></td>
    <td><%= click.clickdate %></td>
    <td><%= link_to 'Show', click %></td>
    <td><%= link_to 'Edit', edit_click_path(click) %></td>
    <td><%= link_to 'Destroy', click, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Click', new_click_path %>

app/views/clicks/new.html.erb
<h1>New click</h1>

<%= render 'form' %>

<%= link_to 'Back', clicks_path %>

app/views/clicks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Referer:</b>
  <%= @click.referer %>
</p>

<p>
  <b>Ip:</b>
  <%= @click.ip %>
</p>

<p>
  <b>Clickdate:</b>
  <%= @click.clickdate %>
</p>


<%= link_to 'Edit', edit_click_path(@click) %> |
<%= link_to 'Back', clicks_path %>